{{- if .Values.langflow.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llmos-agents.langflow.serviceAccountName" . }}
  labels:
    {{- include "llmos-agents.langflow.labels" . | nindent 4 }}
  {{- with .Values.langflow.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.langflow.serviceAccount.automount }}
{{- end }}
