#name: LLMOS Charts
#
#on:
#  pull_request:
#    branches:
#      - main
#      - release-*
#  push:
#    branches:
#      - main
#      - release-*
#
#jobs:
#  lint-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - run: |
#          git remote add upstream https://github.com/llmos-ai/charts.git
#          git fetch upstream
#      - name: Set up Helm
#        uses: azure/setup-helm@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.x'
#          check-latest: true
#      - name: Set up chart-testing
#        uses: helm/chart-testing-action@v2.6.1
#      - name: Run chart-testing (list-changed)
#        id: list-changed
#        run: |
#          changed=$(ct list-changed --config tests/ct.yaml)
#          if [[ -n "$changed" ]]; then
#            echo "::set-output name=changed::true"
#          fi
#      - name: Add repositories
#        run: |
#          for dir in $(ls -d charts/*/); do
#            helm dependency list "$dir" 2> /dev/null | tail +2 | head -n -1 | awk '{ if ($3 != "") print "helm repo add " $1 " " $3 }' | while read cmd; do
#              echo "Executing: $cmd"
#              $cmd || echo "Failed to execute: $cmd"
#            done
#          done
#      - name: Run chart-testing (lint-main)
#        run: |
#          if [ "${{github.base_ref}}" == "main" ]; then
#            echo "validating against ${{github.base_ref}} without version bump validation"
#            ct lint --check-version-increment=false --config tests/ct.yaml
#          else
#            echo "validating against ${{github.base_ref}}"
#            ct lint --config tests/ct.yaml
#          fi
#      - name: Create kind cluster
#        uses: helm/kind-action@v1.10.0
#        if: steps.list-changed.outputs.changed == 'true'
#      - name: Apply k8s required testing resources
#        run: "kubectl apply -f tests/resources/*.yaml"
#        if: steps.list-changed.outputs.changed == 'true'
#      - name: Run chart-testing (install)
#        run: ct install --config tests/ct.yaml
#
#  release-charts:
#    runs-on: ubuntu-latest
#    permissions: write-all
#    needs: lint-test
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#      - name: Install Helm
#        uses: azure/setup-helm@v4
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#      - name: Run chart-releaser
#        uses: guangbochen/chart-releaser-action@main
#        env:
#          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
